BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "NOTETYPES" (
	"Ntp_ID"	INTEGER UNIQUE,
	"Ntp_NAME"	TEXT,
	"Ntp_DESCRIPTION"	TEXT,
	PRIMARY KEY("Ntp_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "USER" (
	"Usr_ID"	INTEGER UNIQUE,
	"Usr_NAME"	TEXT NOT NULL DEFAULT 'USER',
	"Usr_PW"	TEXT,
	"Usr_GROUP"	TEXT DEFAULT 'GROUP',
	PRIMARY KEY("Usr_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "NOTES" (
	"Not_ID"	INTEGER UNIQUE,
	"Not_NAME"	TEXT,
	"Not_NOTES"	TEXT,
	"Not_DATETIME"	TEXT,
	"Not_Usr_ID"	INTEGER NOT NULL,
	"Not_Ntp_ID"	INTEGER NOT NULL,
	PRIMARY KEY("Not_ID" AUTOINCREMENT),
	FOREIGN KEY("Not_Usr_ID") REFERENCES "USER"("Usr_ID"),
	FOREIGN KEY("Not_Ntp_ID") REFERENCES "NOTETYPES"("Ntp_ID")
);
CREATE TABLE IF NOT EXISTS "NOTEMEDIA" (
	"Nmd_ID"	INTEGER UNIQUE,
	"Nmd_DESCRIPTION"	TEXT,
	"Nmd_MEDIA"	BLOB,
	"Nmd_THUMB"	BLOB,
	"Nmd_Not_ID"	INTEGER,
	"Nmd_DATETIME"	TEXT,
	PRIMARY KEY("Nmd_ID" AUTOINCREMENT),
	FOREIGN KEY("Nmd_Not_ID") REFERENCES "NOTES"("Not_ID")
);
INSERT INTO "NOTETYPES" VALUES (1,'Trade','Review Your Trade');
INSERT INTO "NOTETYPES" VALUES (2,'Daily','End of Day Review');
INSERT INTO "NOTETYPES" VALUES (3,'PreWeek','Pre-Week Notes');
INSERT INTO "NOTETYPES" VALUES (4,'PostWeek','Post Week Review');
INSERT INTO "NOTETYPES" VALUES (5,'Rules','Rules You Trade By');
INSERT INTO "NOTETYPES" VALUES (6,'Strategy','Strategies or Setups');
INSERT INTO "NOTETYPES" VALUES (7,'Plan','Lay Out Your Plan');
INSERT INTO "NOTETYPES" VALUES (8,'Workout','Workout Notes');
INSERT INTO "NOTETYPES" VALUES (9,'Diet','Diet Notes');
INSERT INTO "NOTETYPES" VALUES (10,'Sleep','Sleep Notes');
INSERT INTO "NOTETYPES" VALUES (11,'Meditation','Meditation Notes');
INSERT INTO "NOTETYPES" VALUES (12,'Thoughts','Current Thoughts');
INSERT INTO "NOTETYPES" VALUES (13,'Ideas','Ideas to research');
INSERT INTO "NOTETYPES" VALUES (14,'Triggers','What Triggers Emotion');
INSERT INTO "NOTETYPES" VALUES (15,'Other','Other Notes');
INSERT INTO "USER" VALUES (1,'USER',NULL,'GROUP');
COMMIT;
